site_name: DronePG
theme: readthedocs
markdown_extensions:
  - admonition
  - toc:
        permalink: "#"
        baselevel: 2
nav:
  - 'levees.md' 
  - SAFEDAM:
    - Projekt: 'safedam/safedam.md'
    - 'safedam/neo3.md'
    - 'safedam/zawisak.md'
  - 'questions.md'