site_name: DronePG
theme: readthedocs
repo_url: https://github.com/dronepg/docs/
markdown_extensions:
  - admonition
  - toc:
        permalink: "#"
        baselevel: 2
nav:
  - 'levees.md'
  - 'photogrammetry.md'
  - 'lidar.md' 
  - SAFEDAM:
    - Projekt: 'safedam/safedam.md'
    - 'safedam/neo3.md'
    - 'safedam/zawisak.md'
  - 'questions.md'
